apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Loki
    orgId: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://127.0.0.1:8428
    isDefault: true
    editable: false
    jsonData:
      prometheusType: Prometheus
      prometheusVersion: 3.0.0
      timeInterval: 30s

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://127.0.0.1:3100
    editable: false
    jsonData:
      maxLines: 1000
      derivedFields: []
