releaseLabel: true

config:
  modules:
    http_2xx:
      prober: http
      timeout: 10s
      http:
        valid_http_versions: [HTTP/1.1, HTTP/2.0]
        follow_redirects: true
        preferred_ip_protocol: ip4
        tls_config:
          insecure_skip_verify: false

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 96Mi

serviceMonitor:
  selfMonitor:
    enabled: true
    labels:
      release: kps
  enabled: true
  defaults:
    labels:
      release: kps
    interval: 30s
    scrapeTimeout: 15s
    module: http_2xx
  targets:
    - name: localshops-dev-api
      url: http://api.localshops-dev.svc.cluster.local:8000/health/ready
      labels:
        release: kps
        environment: dev
        service: api
        scope: internal
    - name: localshops-dev-app
      url: http://web.localshops-dev.svc.cluster.local:3000/api/health
      labels:
        release: kps
        environment: dev
        service: app
        scope: internal
    - name: localshops-prod-api
      url: http://api.localshops.svc.cluster.local:8000/health/ready
      labels:
        release: kps
        environment: production
        service: api
        scope: internal
    - name: localshops-prod-app
      url: http://web.localshops.svc.cluster.local:3000/
      hostname: app.bhuplabs.dev
      labels:
        release: kps
        environment: production
        service: app
        scope: internal
    - name: keycloak
      url: http://keycloak.keycloak.svc.cluster.local:8080/realms/master/.well-known/openid-configuration
      labels:
        release: kps
        environment: shared
        service: keycloak
        scope: internal
    - name: grafana
      url: http://kps-grafana.monitoring.svc.cluster.local/login
      labels:
        release: kps
        environment: shared
        service: grafana
        scope: internal

networkPolicy:
  enabled: false
