apiVersion: v1
kind: Service
metadata:
  name: traefik-health
  namespace: traefik
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-traefik
  ports:
    - name: health
      port: 8080
      targetPort: traefik
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-n8n-health-route
  namespace: traefik
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: n8n
  to:
    - group: ""
      kind: Service
      name: traefik-health
